package puzzles

import inputs.day09Input
import inputs.day09TestInput
import inputs.day09TestInput2
import kotlin.math.abs
import kotlin.math.round
import kotlin.math.sqrt


fun main() {
    println("day 09 test = ${solveDay09Task(day09TestInput)}")
    println("day 09 = ${solveDay09Task(day09Input)}")
//    println("day 09 part 2 test = ${solveDay09Part2(day09TestInput)}")
    println("day 09 part 2 test 2 = ${solveDay09Part2(day09TestInput2)}")
    println("day 09 part 2 = ${solveDay09Part2(day09Input)}")
}

private data class Rope(var x: Int, var y: Int, val isLast: Boolean = false) {
    fun moveTo(x: Int? = null, y: Int? = null) {
        this.x = x ?: this.x
        this.y = y ?: this.y
    }

    enum class Direction {
        N, NE, E, SE, S, SW, W, NW
    }

    private fun getDirection(other: Rope): Direction {
        if (x == other.x) {
            return if (other.y > y) {
                Direction.N
            } else {
                Direction.S
            }
        }

        if (y == other.y) {
            return if (other.x > x) {
                Direction.E
            } else {
                Direction.W
            }
        }

        return if (other.x > x) {
            if (other.y > y) {
                Direction.NE
            } else {
                Direction.SE
            }
        } else {
            if (other.y > y) {
                Direction.NW
            } else {
                Direction.SW
            }
        }
    }

    private fun getDirection2(other: Rope): Direction {
        return when {
            x == other.x && other.y > y -> Direction.N
            x == other.x && other.y < y -> Direction.S
            y == other.y && other.x > x -> Direction.E
            y == other.y && other.x < x -> Direction.W
            other.x > x && other.y > y -> Direction.NE
            other.x > x && other.y < y -> Direction.SE
            other.x < x && other.y > y -> Direction.NW
            other.x < x && other.y < y -> Direction.SW
            else -> throw IllegalStateException("Unexpected state")
        }
    }

    fun moveTo(other: Rope) {
        when (getDirection(other)) {
            Direction.N -> moveTo(y = y + 1)
            Direction.NE -> moveTo(x = x + 1, y = y + 1)
            Direction.E -> moveTo(x = x + 1)
            Direction.SE -> moveTo(x = x + 1, y = y - 1)
            Direction.S -> moveTo(y = y - 1)
            Direction.SW -> moveTo(x = x - 1, y = y - 1)
            Direction.W -> moveTo(x = x - 1)
            Direction.NW -> moveTo(x = x - 1, y = y + 1)
        }
    }

    fun isOtherInOurRadius(other: Rope): Boolean {
        return (x == other.x && y == other.y)
                || (x + 1 == other.x && y == other.y)
                || (x + 1 == other.x && y + 1 == other.y)
                || (x == other.x && y + 1 == other.y)
                || (x - 1 == other.x && y + 1 == other.y)
                || (x - 1 == other.x && y == other.y)
                || (x - 1 == other.x && y - 1 == other.y)
                || (x == other.x && y - 1 == other.y)
                || (x + 1 == other.x && y - 1 == other.y)
    }

    fun isDistanceMoreThenNumber(other: Rope, number: Int): Boolean {
        fun distance(x1: Int, y1: Int, x2: Int, y2: Int): Int {
            val base = abs(x1) - abs(x2)
            val altitude = abs(y1) - abs(y2)
            return round(sqrt(base * base + altitude * altitude + 0.0)).toInt()
        }

        return distance(x1 = x, y1 = y, x2 = other.x, y2 = other.y) > number
    }
}

private enum class StepDirection {
    U, D, L, R
}

private data class Step(val direction: StepDirection, val count: Int) {
    override fun toString(): String {
        return "$direction $count"
    }
}

private fun parseDay09Input(input: String): List<Step> {
    val stack = mutableListOf<Step>()
    input.lines()
        .map { line ->
            line.split(" ")
        }
        .map { (direction, count) ->
            Step(StepDirection.valueOf(direction), count.toInt())
        }
        .forEach { step ->
            stack.add(step)
        }
    return stack
}

private fun makeTraceKey(tail: Rope): String {
    return "${tail.x} ${tail.y}"
}

/**
 * --- Day 9: Rope Bridge ---
 * This rope bridge creaks as you walk along it. You aren't sure how old it is, or whether it can even support your weight.
 *
 * It seems to support the Elves just fine, though. The bridge spans a gorge which was carved out by the massive river far below you.
 *
 * You step carefully; as you do, the ropes stretch and twist. You decide to distract yourself by modeling rope physics; maybe you can even figure out where not to step.
 *
 * Consider a rope with a knot at each end; these knots mark the head and the tail of the rope. If the head moves far enough away from the tail, the tail is pulled toward the head.
 *
 * Due to nebulous reasoning involving Planck lengths, you should be able to model the positions of the knots on a two-dimensional grid. Then, by following a hypothetical series of motions (your puzzle input) for the head, you can determine how the tail will move.
 *
 * Due to the aforementioned Planck lengths, the rope must be quite short; in fact, the head (H) and tail (T) must always be touching (diagonally adjacent and even overlapping both count as touching):
 *
 * ....
 * .TH.
 * ....
 *
 * ....
 * .H..
 * ..T.
 * ....
 *
 * ...
 * .H. (H covers T)
 * ...
 * If the head is ever two steps directly up, down, left, or right from the tail, the tail must also move one step in that direction so it remains close enough:
 *
 * .....    .....    .....
 * .TH.. -> .T.H. -> ..TH.
 * .....    .....    .....
 *
 * ...    ...    ...
 * .T.    .T.    ...
 * .H. -> ... -> .T.
 * ...    .H.    .H.
 * ...    ...    ...
 * Otherwise, if the head and tail aren't touching and aren't in the same row or column, the tail always moves one step diagonally to keep up:
 *
 * .....    .....    .....
 * .....    ..H..    ..H..
 * ..H.. -> ..... -> ..T..
 * .T...    .T...    .....
 * .....    .....    .....
 *
 * .....    .....    .....
 * .....    .....    .....
 * ..H.. -> ...H. -> ..TH.
 * .T...    .T...    .....
 * .....    .....    .....
 * You just need to work out where the tail goes as the head follows a series of motions. Assume the head and the tail both start at the same position, overlapping.
 *
 * For example:
 *
 * R 4
 * U 4
 * L 3
 * D 1
 * R 4
 * D 1
 * L 5
 * R 2
 * This series of motions moves the head right four steps, then up four steps, then left three steps, then down one step, and so on. After each step, you'll need to update the position of the tail if the step means the head is no longer adjacent to the tail. Visually, these motions occur as follows (s marks the starting position as a reference point):
 *
 * == Initial State ==
 *
 * ......
 * ......
 * ......
 * ......
 * H.....  (H covers T, s)
 *
 * == R 4 ==
 *
 * ......
 * ......
 * ......
 * ......
 * TH....  (T covers s)
 *
 * ......
 * ......
 * ......
 * ......
 * sTH...
 *
 * ......
 * ......
 * ......
 * ......
 * s.TH..
 *
 * ......
 * ......
 * ......
 * ......
 * s..TH.
 *
 * == U 4 ==
 *
 * ......
 * ......
 * ......
 * ....H.
 * s..T..
 *
 * ......
 * ......
 * ....H.
 * ....T.
 * s.....
 *
 * ......
 * ....H.
 * ....T.
 * ......
 * s.....
 *
 * ....H.
 * ....T.
 * ......
 * ......
 * s.....
 *
 * == L 3 ==
 *
 * ...H..
 * ....T.
 * ......
 * ......
 * s.....
 *
 * ..HT..
 * ......
 * ......
 * ......
 * s.....
 *
 * .HT...
 * ......
 * ......
 * ......
 * s.....
 *
 * == D 1 ==
 *
 * ..T...
 * .H....
 * ......
 * ......
 * s.....
 *
 * == R 4 ==
 *
 * ..T...
 * ..H...
 * ......
 * ......
 * s.....
 *
 * ..T...
 * ...H..
 * ......
 * ......
 * s.....
 *
 * ......
 * ...TH.
 * ......
 * ......
 * s.....
 *
 * ......
 * ....TH
 * ......
 * ......
 * s.....
 *
 * == D 1 ==
 *
 * ......
 * ....T.
 * .....H
 * ......
 * s.....
 *
 * == L 5 ==
 *
 * ......
 * ....T.
 * ....H.
 * ......
 * s.....
 *
 * ......
 * ....T.
 * ...H..
 * ......
 * s.....
 *
 * ......
 * ......
 * ..HT..
 * ......
 * s.....
 *
 * ......
 * ......
 * .HT...
 * ......
 * s.....
 *
 * ......
 * ......
 * HT....
 * ......
 * s.....
 *
 * == R 2 ==
 *
 * ......
 * ......
 * .H....  (H covers T)
 * ......
 * s.....
 *
 * ......
 * ......
 * .TH...
 * ......
 * s.....
 * After simulating the rope, you can count up all of the positions the tail visited at least once. In this diagram, s again marks the starting position (which the tail also visited) and # marks other positions the tail visited:
 *
 * ..##..
 * ...##.
 * .####.
 * ....#.
 * s###..
 * So, there are 13 positions the tail visited at least once.
 *
 * Simulate your complete hypothetical series of motions. How many positions does the tail of the rope visit at least once?
 */
fun solveDay09Task(input: String): Int {
    val head = Rope(0, 0)
    val tail = Rope(0, 0)

    val tailTrace = mutableSetOf<String>()
    tailTrace.add(makeTraceKey(tail))

    val steps = parseDay09Input(input)

    steps.forEach { step ->
        repeat(step.count) {
            val prevHead = head.copy()

            when (step.direction) {
                StepDirection.U -> head.moveTo(y = head.y + 1)
                StepDirection.D -> head.moveTo(y = head.y - 1)
                StepDirection.L -> head.moveTo(x = head.x - 1)
                StepDirection.R -> head.moveTo(x = head.x + 1)
            }

            if (!tail.isOtherInOurRadius(head)) {
                tail.moveTo(prevHead)
                tailTrace.add(makeTraceKey(tail))
            }
        }
    }

    return tailTrace.size
}

/**
 * --- Part Two ---
 * A rope snaps! Suddenly, the river is getting a lot closer than you remember. The bridge is still there, but some of the ropes that broke are now whipping toward you as you fall through the air!
 *
 * The ropes are moving too quickly to grab; you only have a few seconds to choose how to arch your body to avoid being hit. Fortunately, your simulation can be extended to support longer ropes.
 *
 * Rather than two knots, you now must simulate a rope consisting of ten knots. One knot is still the head of the rope and moves according to the series of motions. Each knot further down the rope follows the knot in front of it using the same rules as before.
 *
 * Using the same series of motions as the above example, but with the knots marked H, 1, 2, ..., 9, the motions now occur as follows:
 *
 * == Initial State ==
 *
 * ......
 * ......
 * ......
 * ......
 * H.....  (H covers 1, 2, 3, 4, 5, 6, 7, 8, 9, s)
 *
 * == R 4 ==
 *
 * ......
 * ......
 * ......
 * ......
 * 1H....  (1 covers 2, 3, 4, 5, 6, 7, 8, 9, s)
 *
 * ......
 * ......
 * ......
 * ......
 * 21H...  (2 covers 3, 4, 5, 6, 7, 8, 9, s)
 *
 * ......
 * ......
 * ......
 * ......
 * 321H..  (3 covers 4, 5, 6, 7, 8, 9, s)
 *
 * ......
 * ......
 * ......
 * ......
 * 4321H.  (4 covers 5, 6, 7, 8, 9, s)
 *
 * == U 4 ==
 *
 * ......
 * ......
 * ......
 * ....H.
 * 4321..  (4 covers 5, 6, 7, 8, 9, s)
 *
 * ......
 * ......
 * ....H.
 * .4321.
 * 5.....  (5 covers 6, 7, 8, 9, s)
 *
 * ......
 * ....H.
 * ....1.
 * .432..
 * 5.....  (5 covers 6, 7, 8, 9, s)
 *
 * ....H.
 * ....1.
 * ..432.
 * .5....
 * 6.....  (6 covers 7, 8, 9, s)
 *
 * == L 3 ==
 *
 * ...H..
 * ....1.
 * ..432.
 * .5....
 * 6.....  (6 covers 7, 8, 9, s)
 *
 * ..H1..
 * ...2..
 * ..43..
 * .5....
 * 6.....  (6 covers 7, 8, 9, s)
 *
 * .H1...
 * ...2..
 * ..43..
 * .5....
 * 6.....  (6 covers 7, 8, 9, s)
 *
 * == D 1 ==
 *
 * ..1...
 * .H.2..
 * ..43..
 * .5....
 * 6.....  (6 covers 7, 8, 9, s)
 *
 * == R 4 ==
 *
 * ..1...
 * ..H2..
 * ..43..
 * .5....
 * 6.....  (6 covers 7, 8, 9, s)
 *
 * ..1...
 * ...H..  (H covers 2)
 * ..43..
 * .5....
 * 6.....  (6 covers 7, 8, 9, s)
 *
 * ......
 * ...1H.  (1 covers 2)
 * ..43..
 * .5....
 * 6.....  (6 covers 7, 8, 9, s)
 *
 * ......
 * ...21H
 * ..43..
 * .5....
 * 6.....  (6 covers 7, 8, 9, s)
 *
 * == D 1 ==
 *
 * ......
 * ...21.
 * ..43.H
 * .5....
 * 6.....  (6 covers 7, 8, 9, s)
 *
 * == L 5 ==
 *
 * ......
 * ...21.
 * ..43H.
 * .5....
 * 6.....  (6 covers 7, 8, 9, s)
 *
 * ......
 * ...21.
 * ..4H..  (H covers 3)
 * .5....
 * 6.....  (6 covers 7, 8, 9, s)
 *
 * ......
 * ...2..
 * ..H1..  (H covers 4; 1 covers 3)
 * .5....
 * 6.....  (6 covers 7, 8, 9, s)
 *
 * ......
 * ...2..
 * .H13..  (1 covers 4)
 * .5....
 * 6.....  (6 covers 7, 8, 9, s)
 *
 * ......
 * ......
 * H123..  (2 covers 4)
 * .5....
 * 6.....  (6 covers 7, 8, 9, s)
 *
 * == R 2 ==
 *
 * ......
 * ......
 * .H23..  (H covers 1; 2 covers 4)
 * .5....
 * 6.....  (6 covers 7, 8, 9, s)
 *
 * ......
 * ......
 * .1H3..  (H covers 2, 4)
 * .5....
 * 6.....  (6 covers 7, 8, 9, s)
 * Now, you need to keep track of the positions the new tail, 9, visits. In this example, the tail never moves, and so it only visits 1 position. However, be careful: more types of motion are possible than before, so you might want to visually compare your simulated rope to the one above.
 *
 * Here's a larger example:
 *
 * R 5
 * U 8
 * L 8
 * D 3
 * R 17
 * D 10
 * L 25
 * U 20
 * These motions occur as follows (individual steps are not shown):
 *
 * == Initial State ==
 *
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ...........H..............  (H covers 1, 2, 3, 4, 5, 6, 7, 8, 9, s)
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 *
 * == R 5 ==
 *
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ...........54321H.........  (5 covers 6, 7, 8, 9, s)
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 *
 * == U 8 ==
 *
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ................H.........
 * ................1.........
 * ................2.........
 * ................3.........
 * ...............54.........
 * ..............6...........
 * .............7............
 * ............8.............
 * ...........9..............  (9 covers s)
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 *
 * == L 8 ==
 *
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ........H1234.............
 * ............5.............
 * ............6.............
 * ............7.............
 * ............8.............
 * ............9.............
 * ..........................
 * ..........................
 * ...........s..............
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 *
 * == D 3 ==
 *
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * .........2345.............
 * ........1...6.............
 * ........H...7.............
 * ............8.............
 * ............9.............
 * ..........................
 * ..........................
 * ...........s..............
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 *
 * == R 17 ==
 *
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ................987654321H
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ...........s..............
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 *
 * == D 10 ==
 *
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ...........s.........98765
 * .........................4
 * .........................3
 * .........................2
 * .........................1
 * .........................H
 *
 * == L 25 ==
 *
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ...........s..............
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * H123456789................
 *
 * == U 20 ==
 *
 * H.........................
 * 1.........................
 * 2.........................
 * 3.........................
 * 4.........................
 * 5.........................
 * 6.........................
 * 7.........................
 * 8.........................
 * 9.........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ...........s..............
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 *
 * Now, the tail (9) visits 36 positions (including s) at least once:
 *
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * ..........................
 * #.........................
 * #.............###.........
 * #............#...#........
 * .#..........#.....#.......
 * ..#..........#.....#......
 * ...#........#.......#.....
 * ....#......s.........#....
 * .....#..............#.....
 * ......#............#......
 * .......#..........#.......
 * ........#........#........
 * .........########.........
 * Simulate your complete series of motions on a larger rope with ten knots. How many positions does the tail of the rope visit at least once?
 */
fun solveDay09Part2(input: String): Int {
    val ropes = listOf(
        Rope(0, 0),
        Rope(0, 0),
        Rope(0, 0),
        Rope(0, 0),
        Rope(0, 0),
        Rope(0, 0),
        Rope(0, 0),
        Rope(0, 0),
        Rope(0, 0),
        Rope(0, 0, true),
    )
    val tailTrace = mutableSetOf<String>()
    tailTrace.add(makeTraceKey(ropes.last()))

    val steps = parseDay09Input(input)

    steps.forEach { step ->
        repeat(step.count) {
            when (step.direction) {
                StepDirection.U -> ropes.first().moveTo(y = ropes.first().y + 1)
                StepDirection.D -> ropes.first().moveTo(y = ropes.first().y - 1)
                StepDirection.L -> ropes.first().moveTo(x = ropes.first().x - 1)
                StepDirection.R -> ropes.first().moveTo(x = ropes.first().x + 1)
            }

            for (i: Int in 1 until ropes.size) {
                val rope = ropes[i]
                if (rope.isDistanceMoreThenNumber(ropes.first(), i + 1)) {
                    // move
                    rope.moveTo(ropes.first())

                    if (rope.isLast) {
                        tailTrace.add(makeTraceKey(ropes.last()))
                    }
                }
            }
        }
    }

    println("tail = $tailTrace")

    return tailTrace.size
}
